load_module /usr/lib/nginx/modules/ngx_stream_module.so;

worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /run/nginx-sni.pid;

events {
    worker_connections 4096;
}

stream {
    map $ssl_preread_server_name $backend {
        cloudflare.com      127.0.0.1:13128;
        www.cloudflare.com  127.0.0.1:10443;
        default             127.0.0.1:10443;
    }

    server {
        listen 127.0.0.1:10440;
        ssl_preread on;
        proxy_pass $backend;
        proxy_timeout 10m;
        proxy_connect_timeout 10s;
    }
}
